format = """
$custom\
$aws\
$directory\
$git_branch\
$docker_context\
$cmd_duration\
$character
"""

[aws]
symbol = "☁️"
format = '@ [$symbol \($region\)]($style) '
style = "bold yellow"

[cmd_duration]
min_time = 1_000
show_milliseconds = true

[directory]
truncation_length = 8

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
disabled = true

[nodejs]
disabled = true

[terraform]
disabled = true

[custom.k8s_cluster]
command = 'echo $(echo $KUBE_CONTEXT_SHORT) \($(echo $KUBE_CURRENT_NS)\)'
when = 'test -n "$KUBE_CONTEXT_SHORT"'
format = '[☸ $output]($style) '
style = 'bold blue'

# 上記customはテスト運用
# パフォーマンス悪ければ戻す
#[kubernetes]
#symbol = "☸ "
#format = '[$symbol$context( \($namespace\))]($style) '
#disabled = false
